[package]
name        = "trivert_utility"
version     = "0.1.0"
authors     = ["Kyle Finlay <kyle.finlay01@gmail.com>"]
description = "Utility functions for use within TriVert"
license     = "Apache-2.0"

[lib]
name = "trivert_utility"
path = "src/lib.rs"
