[package]
name        = "trivert_math"
version     = "0.1.0"
authors     = ["Kyle Finlay <kyle.finlay01@gmail.com>"]
description = "Math library for TriVert"
license     = "BSD-3-Clause"

[lib]
name = "trivert_math"
path = "src/lib.rs"
